# sudo: false

# 2019-04-30 15:14 UTC

matrix:
  include:
    - os: linux
      dist: trusty
      env: os="trusty 14.04"
    - os: linux
      dist: xenial
      env: os="xenial 16.04"
    - os: linux
      dist: bionic
      env: os="bionic 18.04"
    - os: osx
      osx_image: xcode10.2
      env: os="osx xcode 10.2"

script:
  - /bin/bash --login "run_vers.sh"
