# sudo: false

# 2019-04-30 15:14 UTC

dist: xenial

osx_image: xcode10.2

matrix:
  include:
    - os: linux
      env: what=xenial
    - os: osx
      env: what=osx_xcode10.2

script:
  - /bin/bash --login "run_vers.sh"
