# sudo: false

# 2019-04-30 15:14 UTC

matrix:
  include:
    - os: linux
      dist: bionic
      env: os="bionic 18.04"
    - os: osx
      osx_image: xcode12.2
      env: os="osx 10.15.7 xcode 12.2"

script:
  - /bin/bash --login "run_vers.sh"
